version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          command: 'node index.js'
          post-steps:
            - store_artifacts:
                path: mochawesome-report
            - store_artifacts:
                path: screenshots
            - store_artifacts:
                path: videos
